/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JMenu;
import javax.swing.JMenuBar;

/**
 *
 * @author USER
 */
public class jMenu extends javax.swing.JFrame {

    /**
     * Creates new form jMenu
     */
    public jMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnProyek = new javax.swing.JMenu();
        mnTugas = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnProyek.setText("Proyek");
        jMenuBar1.add(mnProyek);

        mnTugas.setText("Tugas");
        jMenuBar1.add(mnTugas);

        mnLogout.setText("Logout");
        jMenuBar1.add(mnLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JMenu getmnProyek() {
        return mnProyek;
    }

    public JMenu getmnTugas() {
        return mnTugas;
    }

    public JMenu getmnLogout() {
        return mnLogout;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenu mnProyek;
    private javax.swing.JMenu mnTugas;
    // End of variables declaration//GEN-END:variables
}
